version: "3.3"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:33060
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQLDB_DATABASE=document
  spring:
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8086:8086"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" :"root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
  frontend:
    image: amenih/talancdz
    restart: unless-stopped
    ports:
      - 2020:80
    depends_on:
      - spring
volumes:
  data :
